apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: test-static
spec:
  rules:
  - host: gloofoo.xyz
    http:
      paths:
      - backend:
          servicePort: http
  - host: edge.gloofoo.xyz
    http:
      paths:
      - backend:
          serviceName: edge-envoy
          servicePort: grpc