package(default_visibility = ["//visibility:public"])

cc_library(
    name = "battleship",
    srcs = ["battleship.cc"],
    hdrs = ["battleship.h"],
    deps = [
        "//battleships:block"
    ],
)

cc_library(
    name = "block",
    hdrs = ["block.h"],
    deps = [
    ],
)

cc_library(
    name = "player",
    srcs = ["player.cc"],
    hdrs = ["player.h"],
    deps = [
    ],
)

