#!/bin/bash

# Transcodes, segments, and uploads videos to Google Storage.
#
# Tech specs:
# - Encodes with x264 for video and aac for audio.
# - Changes to 60fps with a keyframe every 240 frames (4s)
# - Segments into 4s chunks.
# - Transcodes to multiple resolutions:
#   - 480p w/ bitrate 1.5Mb/s for video and 128Kb/s for audio
#   - 720p w/ bitrate 9.5Mb/s for video and 384Kb/s for audio
#
# Flags:
# --video              video file (eg: foo.mp4, bar.mkv, baz.ogg)
# --output_dir         output directory (a gs:// path)

source "$(git rev-parse --show-toplevel)/tash/tash.sh" || exit 1
pushd  "$(dirname "$0")" > /dev/null

assert_linux

declare_string video '' required
declare_string output_dir '' required
parse_args "$@"

assert_not_empty "${FLAGS_video:?}"
assert_not_empty "${FLAGS_output_dir:?}"
assert_matches_regex "$FLAGS_output_dir" "^gs://.*$"

readonly GS_PATH="$(echo "$FLAGS_output_dir" | cut -c 6- | sed 's:/*$::')"

pushd "$(mktemp -d)" > /dev/null
log info "Using temp directory $(pwd)"

# ---------------------------------- Transcode ---------------------------------

mkdir transcoded
pushd transcoded > /dev/null

ffmpeg \
    -i "$FLAGS_video" \
    -c:v libx264 -c:a aac \
    -vf scale=-1:480 \
    -b:v 1.5M -b:a 128k \
    -filter:v fps=fps=60 \
    -g 240 -keyint_min 240 -sc_threshold 0 \
    -profile:v main \
    -threads 0 \
    -strict 1 \
    -movflags +faststart \
    480p.mp4 \
    -hide_banner
assert_last_command_ok

ffmpeg \
    -i "$FLAGS_video" \
    -c:v libx264 -c:a aac \
    -vf scale=-1:720 \
    -b:v 9.5M -b:a 384k \
    -filter:v fps=fps=60 \
    -g 240 -keyint_min 240 -sc_threshold 0 \
    -profile:v main \
    -threads 0 \
    -strict 1 \
    -movflags +faststart \
    720p.mp4 \
    -hide_banner
assert_last_command_ok

popd > /dev/null  # transcoded

# ----------------------------------- Segment ----------------------------------

MP4Box \
    -dash 4000 \
    -fps 60 \
    -mpd-title 'Generated by Terrace Video, Co.' \
    -rap -frag-rap \
    -profile dashavc264:live \
    -bs-switching inband \
    -segment-name '' \
    -url-template \
    -base-url "https://storage.googleapis.com/${GS_PATH}/manifest.mpd" \
    -out manifest \
    transcoded/480p.mp4#video:baseURL=v480 \
    transcoded/480p.mp4#audio:baseURL=a480 \
    transcoded/720p.mp4#video:baseURL=v720 \
    transcoded/720p.mp4#audio:baseURL=a720
assert_last_command_ok

# ----------------------------------- Cleanup ----------------------------------

rm -r transcoded
assert_last_command_ok

# ----------------------------------- Upload -----------------------------------

gsutil -m cp -r . "$FLAGS_output_dir"
assert_last_command_ok

log ok 'Done'
popd > /dev/null  # "$(mktemp -d)"
