apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: gcr.io/grpc-react-test/echo_server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - "/bin/grpc_health_client"
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - "/bin/grpc_health_client"
          initialDelaySeconds: 30
          periodSeconds: 5