package(default_visibility = ["//visibility:public"])

cc_library(
    name = "flags",
    srcs = ["flags.cc"],
    hdrs = ["flags.h"],
    deps = [
        "@com_github_abseil_absl//absl/flags:flag",
        "@com_github_abseil_absl//absl/flags:parse",
        "@com_github_gflags_gflags//:gflags",
    ],
)